feat: ASG Tag lambda function
ydataai/aws-asg-tags-lambda pull request #7
Opened 2022-06-21 00:08 UTC by portellaa

2022-06-22 14:22 UTC, andre-lx approved these changes

2022-06-22 14:22 UTC, andre-lx commented on README.md
> +          - 'lambda-asg-tag'
please remove the 'ydata-platform'

2022-06-23 12:26 UTC, renatoaguimaraes approved these changes

2022-06-23 13:53 UTC, andre-lx requested changes

2022-06-23 13:56 UTC, andre-lx approved these changes

2022-06-23 14:19 UTC, merged